<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>RyzaEsPatcher.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\third_party\hdiffpatch\win-x64\hpatchz.exe" LogicalName="hpatchz.exe" />
  </ItemGroup>

</Project>
